# Generated by Django 4.1.7 on 2023-02-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('ca', models.FloatField()),
                ('se', models.FloatField()),
                ('grade', models.CharField(max_length=2)),
            ],
        ),
    ]
