# Generated by Django 4.1.7 on 2023-02-26 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='registration_number',
        ),
    ]
